name: 'Warden'
description: 'Event-driven agent that analyzes GitHub PRs using Claude Code SDK'
author: 'Functional Software, Inc.'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  anthropic-api-key:
    description: 'Anthropic API key for Claude Code SDK. Can also be provided via WARDEN_ANTHROPIC_API_KEY environment variable.'
    required: false
  github-token:
    description: 'GitHub token for API access (defaults to GITHUB_TOKEN)'
    required: false
    default: ${{ github.token }}
  config-path:
    description: 'Path to warden.toml config file (relative to repo root)'
    required: false
    default: 'warden.toml'
  fail-on:
    description: 'Minimum severity level to fail the action (critical, high, medium, low, info)'
    required: false
  max-findings:
    description: 'Maximum number of findings to report (0 for unlimited)'
    required: false
    default: '50'
  parallel:
    description: 'Maximum number of concurrent trigger executions'
    required: false
    default: '5'

outputs:
  findings-count:
    description: 'Total number of findings'
    value: ${{ steps.warden.outputs.findings-count }}
  critical-count:
    description: 'Number of critical severity findings'
    value: ${{ steps.warden.outputs.critical-count }}
  high-count:
    description: 'Number of high severity findings'
    value: ${{ steps.warden.outputs.high-count }}
  summary:
    description: 'Summary of the analysis'
    value: ${{ steps.warden.outputs.summary }}

runs:
  using: 'composite'
  steps:
    - name: Install Claude Code CLI
      shell: bash
      run: |
        CLAUDE_CODE_VERSION="2.1.23"
        echo "Installing Claude Code v${CLAUDE_CODE_VERSION}..."
        for attempt in 1 2 3; do
          echo "Installation attempt $attempt..."
          if curl -fsSL https://claude.ai/install.sh | bash -s -- "$CLAUDE_CODE_VERSION"; then
            break
          fi
          if [ $attempt -eq 3 ]; then
            echo "Failed to install Claude Code after 3 attempts"
            exit 1
          fi
          echo "Installation failed, retrying..."
          sleep 5
        done
        echo "Claude Code installed successfully"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

    - name: Run Warden
      id: warden
      shell: bash
      env:
        INPUT_ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_CONFIG_PATH: ${{ inputs.config-path }}
        INPUT_FAIL_ON: ${{ inputs.fail-on }}
        INPUT_MAX_FINDINGS: ${{ inputs.max-findings }}
        INPUT_PARALLEL: ${{ inputs.parallel }}
        CLAUDE_CODE_PATH: ${{ env.HOME }}/.local/bin/claude
      run: node ${{ github.action_path }}/dist/action/index.js
