/**
 * Pushes a pricing update branch and opens/refreshes a PR.
 *
 * Expected pre-state:
 *   - `pnpm update-pricing` has just run and may have changed
 *     packages/warden/src/sdk/model-pricing.json.
 *   - The working tree contains at most that single file change.
 *   - The shell environment has a writable GITHUB_TOKEN (or the
 *     remote is otherwise authenticated for both git push and gh).
 *
 * Behavior:
 *   - Treats origin/main as the source of truth.
 *   - The automation branch is disposable: each run recreates it from
 *     current origin/main, plops the freshly generated file on top, and
 *     pushes with --force-with-lease.
 *   - If the generated file already matches origin/main, exits quietly.
 *   - If an open PR already targets the automation branch, the force-pushed
 *     branch updates it automatically. Otherwise a new PR is opened.
 *
 * Usage: pnpm --filter @sentry/warden update-pricing-pr
 */

import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, copyFileSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const AUTOMATION_BRANCH = 'automation/update-model-pricing';
const BASE_BRANCH = 'main';
const PRICING_FILE = 'packages/warden/src/sdk/model-pricing.json';
const COMMIT_MESSAGE = 'chore: update model pricing';
const PR_TITLE = 'chore: update model pricing';
const PR_BODY =
  'Automated update of model pricing from [`pydantic/genai-prices`](https://github.com/pydantic/genai-prices).\n' +
  '\n' +
  'Generated by `.github/workflows/update-pricing.yml`.';

function run(command: string, args: string[], options: { cwd?: string } = {}): string {
  return execFileSync(command, args, {
    cwd: options.cwd,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'inherit'],
  }).trimEnd();
}

function runAllowFail(
  command: string,
  args: string[],
): { status: number | null; stdout: string; stderr: string } {
  const result = spawnSync(command, args, { encoding: 'utf8' });
  return {
    status: result.status,
    stdout: (result.stdout ?? '').trimEnd(),
    stderr: (result.stderr ?? '').trimEnd(),
  };
}

function fail(message: string): never {
  console.error(`error: ${message}`);
  process.exit(1);
}

function assertCleanExceptPricing(): void {
  const status = run('git', ['status', '--porcelain', '--', '.']);
  if (status === '') {
    return;
  }
  const lines = status.split('\n');
  for (const line of lines) {
    // Porcelain v1 format: XY <path>
    const path = line.slice(3);
    if (path !== PRICING_FILE) {
      fail(
        `unexpected working tree change: ${line}. ` +
          `Only ${PRICING_FILE} may be modified before running this script.`,
      );
    }
  }
}

function fetchRefs(): { automationSha: string | null } {
  // origin/main is required; the automation branch may not exist yet.
  run('git', ['fetch', '--no-tags', 'origin', BASE_BRANCH]);
  const result = runAllowFail('git', [
    'fetch',
    '--no-tags',
    'origin',
    AUTOMATION_BRANCH,
  ]);
  if (result.status !== 0) {
    // A missing remote branch is expected on the first run; surface other
    // failures (network, permissions) instead of pretending all is well.
    if (result.stderr && !/couldn't find remote ref/i.test(result.stderr)) {
      fail(`git fetch ${AUTOMATION_BRANCH} failed: ${result.stderr}`);
    }
    return { automationSha: null };
  }
  const sha = runAllowFail('git', [
    'rev-parse',
    `refs/remotes/origin/${AUTOMATION_BRANCH}`,
  ]);
  return { automationSha: sha.status === 0 ? sha.stdout : null };
}

function readFileFromRef(ref: string, path: string): string | null {
  const result = runAllowFail('git', ['show', `${ref}:${path}`]);
  if (result.status !== 0) {
    return null;
  }
  return result.stdout;
}

function findOpenPrNumber(): number | null {
  const result = runAllowFail('gh', [
    'pr',
    'list',
    '--head',
    AUTOMATION_BRANCH,
    '--base',
    BASE_BRANCH,
    '--state',
    'open',
    '--json',
    'number',
    '--jq',
    '.[0].number',
  ]);
  if (result.status !== 0) {
    fail(`gh pr list failed: ${result.stderr}`);
  }
  if (result.stdout === '') {
    return null;
  }
  const n = Number(result.stdout);
  return Number.isFinite(n) ? n : null;
}

function configureGitIdentity(): void {
  // Honour CI-provided identity (e.g. from actions/create-github-app-token);
  // otherwise leave whatever the local config has.
  const name = process.env.GIT_AUTHOR_NAME ?? process.env.GIT_COMMITTER_NAME;
  const email = process.env.GIT_AUTHOR_EMAIL ?? process.env.GIT_COMMITTER_EMAIL;
  if (name) {
    run('git', ['config', 'user.name', name]);
  }
  if (email) {
    run('git', ['config', 'user.email', email]);
  }
}

async function main(): Promise<void> {
  assertCleanExceptPricing();

  const generated = readFileSync(PRICING_FILE, 'utf8');

  const { automationSha } = fetchRefs();

  const baseline = readFileFromRef(`origin/${BASE_BRANCH}`, PRICING_FILE);
  if (baseline === null) {
    fail(`could not read ${PRICING_FILE} from origin/${BASE_BRANCH}`);
  }

  if (generated === baseline) {
    console.log('Model pricing matches origin/main; nothing to do.');
    return;
  }

  // Stash the generated file outside the worktree so a clean checkout of
  // origin/main does not clobber it.
  const tmpDir = mkdtempSync(join(tmpdir(), 'warden-pricing-'));
  const tmpFile = join(tmpDir, 'model-pricing.json');
  writeFileSync(tmpFile, generated);

  configureGitIdentity();

  // Reset to a clean origin/main checkout, then overlay the generated file.
  // `switch -C` will refuse to discard the pricing change; reset it first.
  run('git', ['checkout', '--', PRICING_FILE]);
  run('git', ['switch', '-C', AUTOMATION_BRANCH, `origin/${BASE_BRANCH}`]);

  copyFileSync(tmpFile, PRICING_FILE);
  run('git', ['add', '--', PRICING_FILE]);
  run('git', ['commit', '-m', COMMIT_MESSAGE]);

  // Use an explicit lease value so behavior is predictable regardless of
  // whether the local branch has an upstream configured. On first run there
  // is no remote ref, so we additionally pass --force-if-includes via a
  // missing-lease ("=<ref>:" with no value) to require the remote branch to
  // not exist.
  const leaseArg =
    automationSha !== null
      ? `--force-with-lease=${AUTOMATION_BRANCH}:${automationSha}`
      : `--force-with-lease=${AUTOMATION_BRANCH}:`;
  const push = runAllowFail('git', [
    'push',
    leaseArg,
    'origin',
    `${AUTOMATION_BRANCH}:${AUTOMATION_BRANCH}`,
  ]);
  if (push.status !== 0) {
    fail(
      `git push --force-with-lease failed; refusing to overwrite. ` +
        `stderr: ${push.stderr}`,
    );
  }
  if (push.stdout) console.log(push.stdout);
  if (push.stderr) console.error(push.stderr);

  const existing = findOpenPrNumber();
  if (existing !== null) {
    console.log(`Updated existing PR #${existing}.`);
    return;
  }

  const create = runAllowFail('gh', [
    'pr',
    'create',
    '--base',
    BASE_BRANCH,
    '--head',
    AUTOMATION_BRANCH,
    '--title',
    PR_TITLE,
    '--body',
    PR_BODY,
  ]);
  if (create.status !== 0) {
    fail(`gh pr create failed: ${create.stderr}`);
  }
  if (create.stdout) console.log(create.stdout);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
