import { spawnSync } from 'node:child_process';
import { closeSync, existsSync, openSync, readSync, statSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import ignore from 'ignore';
import { DEFAULT_SCAN_LIMITS, type IgnoreConfig, type ScanConfig } from '../config/schema.js';
import type { DiffContextSource, FileChange, SkippedFile } from '../types/index.js';
import { GIT_NON_INTERACTIVE_ENV } from '../utils/exec.js';
import { isRepoRelativePath, normalizePath } from '../utils/path.js';

const GENERATED_PREFIX_BYTES = 64 * 1024;
const GENERATED_PREFIX_LINES = 200;

const BUILTIN_IGNORE_PATTERNS = [
  '**/pnpm-lock.yaml',
  '**/package-lock.json',
  '**/yarn.lock',
  '**/Cargo.lock',
  '**/go.sum',
  '**/poetry.lock',
  '**/composer.lock',
  '**/Gemfile.lock',
  '**/Pipfile.lock',
  '**/bun.lockb',
  '**/*.min.js',
  '**/*.min.css',
  '**/*.bundle.js',
  '**/*.bundle.css',
  '**/*.map',
  '**/dist/**',
  '**/build/**',
  '**/node_modules/**',
  '**/vendor/**',
  '**/.next/**',
  '**/.nuxt/**',
  '**/out/**',
  '**/coverage/**',
  '**/.cache/**',
  '**/*.generated.*',
  '**/*.g.ts',
  '**/*.g.dart',
  '**/*.pb.go',
  '**/*_pb2.py',
  '**/*.designer.cs',
  '**/generated/**',
  '**/__generated__/**',
  '**/*.png',
  '**/*.jpg',
  '**/*.jpeg',
  '**/*.gif',
  '**/*.webp',
  '**/*.ico',
  '**/*.svg',
  '**/*.pdf',
  '**/*.zip',
  '**/*.tar',
  '**/*.tgz',
  '**/*.gz',
  '**/*.woff',
  '**/*.woff2',
  '**/*.ttf',
  '**/*.mp4',
  '**/*.mov',
  '**/*.sqlite',
  '**/*.db',
  '**/*.parquet',
  '**/*.csv',
  '**/*.tsv',
];

const GENERATED_MARKER_PATTERNS = [
  /@generated\b/i,
  /\bautomatically generated\b/i,
  /\bcode generated by\b/i,
  /\bgenerated from\b/i,
  /\bopenapi generator\b/i,
  /\bswagger codegen\b/i,
  /\bgraphql-codegen\b/i,
  /\bgenerated by protoc\b/i,
];

export interface ScanPolicyOptions {
  repoPath: string;
  ignore?: IgnoreConfig;
  scan?: ScanConfig;
  diffContextSource?: DiffContextSource;
  /** Whether to enforce PR/diff changed-line scan budgets. Defaults to true. */
  enforceChangedLineBudget?: boolean;
}

export type ScannableFileChange = FileChange & { patch: string };

export interface ApplyScanPolicyResult {
  files: ScannableFileChange[];
  skippedFiles: SkippedFile[];
}

function changedLines(file: FileChange): number {
  return file.additions + file.deletions;
}

function effectiveScanConfig(config?: ScanConfig): Required<ScanConfig> {
  return {
    ...DEFAULT_SCAN_LIMITS,
    ...config,
  };
}

function stripNegation(pattern: string): string {
  return pattern.startsWith('!') ? pattern.slice(1) : pattern;
}

function matchesIgnorePattern(filename: string, pattern: string): boolean {
  return ignore().add(stripNegation(pattern)).ignores(filename);
}

function userIncludesFile(filename: string, paths?: string[]): boolean {
  return (paths ?? []).some((pattern) => pattern.startsWith('!') && matchesIgnorePattern(filename, pattern));
}

function ignoredByBuiltinOrUser(filename: string, config?: IgnoreConfig): SkippedFile | undefined {
  let skip: SkippedFile | undefined;

  // Built-ins establish the baseline; user paths replay afterward in order so
  // later `!` patterns can re-include files.
  for (const pattern of BUILTIN_IGNORE_PATTERNS) {
    if (matchesIgnorePattern(filename, pattern)) {
      skip = { filename, reason: 'ignored:builtin' };
    }
  }

  for (const pattern of config?.paths ?? []) {
    if (!matchesIgnorePattern(filename, pattern)) {
      continue;
    }

    skip = pattern.startsWith('!')
      ? undefined
      : { filename, reason: 'ignored:user', pattern };
  }

  return skip;
}

function filePathFor(repoPath: string, filename: string): string | undefined {
  const root = resolve(repoPath);
  const filePath = resolve(join(repoPath, filename));
  const relativePath = normalizePath(relative(root, filePath));
  if (!isRepoRelativePath(relativePath)) {
    return undefined;
  }
  return filePath;
}

function readPrefix(filePath: string, maxBytes: number): string | undefined {
  let fd: number | undefined;
  try {
    fd = openSync(filePath, 'r');
    const buffer = Buffer.alloc(maxBytes);
    const bytesRead = readSync(fd, buffer, 0, maxBytes, 0);
    return buffer.toString('utf-8', 0, bytesRead);
  } catch {
    return undefined;
  } finally {
    if (fd !== undefined) {
      closeSync(fd);
    }
  }
}

type SourceReadResult =
  | { type: 'content'; content: Buffer }
  | { type: 'too_large' }
  | { type: 'unavailable' };

/** Convert non-working-tree sources to the git-show refspec used for content reads. */
function sourceRefPath(filename: string, source: DiffContextSource): string | undefined {
  if (source.type === 'working-tree') {
    return undefined;
  }

  return source.type === 'git-index'
    ? `:${filename}`
    : `${source.ref}:${filename}`;
}

function readGitSource(repoPath: string, filename: string, source: DiffContextSource, maxBytes: number): SourceReadResult {
  const refPath = sourceRefPath(filename, source);
  if (!refPath) {
    return { type: 'unavailable' };
  }

  const result = spawnSync('git', ['show', refPath], {
    cwd: repoPath,
    encoding: 'buffer',
    env: { ...process.env, ...GIT_NON_INTERACTIVE_ENV },
    maxBuffer: maxBytes + 1,
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  if (result.error) {
    const error = result.error as Error & { code?: string };
    return error.code === 'ENOBUFS'
      ? { type: 'too_large' }
      : { type: 'unavailable' };
  }

  if (result.status !== 0 || !Buffer.isBuffer(result.stdout)) {
    return { type: 'unavailable' };
  }

  if (result.stdout.length > maxBytes) {
    return { type: 'too_large' };
  }

  return { type: 'content', content: result.stdout };
}

function countLinesUpTo(filePath: string, maxLines: number): number | undefined {
  let fd: number | undefined;
  try {
    fd = openSync(filePath, 'r');
    const buffer = Buffer.alloc(64 * 1024);
    let lines = 0;
    let sawBytes = false;
    let lastByteWasNewline = false;
    while (true) {
      const bytesRead = readSync(fd, buffer, 0, buffer.length, null);
      if (bytesRead === 0) {
        if (!sawBytes) return 0;
        return lastByteWasNewline ? lines : lines + 1;
      }
      sawBytes = true;
      for (let i = 0; i < bytesRead; i++) {
        if (buffer[i] === 10) {
          lines++;
          if (lines > maxLines) return lines;
        }
      }
      lastByteWasNewline = buffer[bytesRead - 1] === 10;
    }
  } catch {
    return undefined;
  } finally {
    if (fd !== undefined) {
      closeSync(fd);
    }
  }
}

function countBufferLinesUpTo(content: Buffer, maxLines: number): number {
  if (content.length === 0) {
    return 0;
  }

  let lines = 0;
  for (const byte of content) {
    if (byte === 10) {
      lines++;
      if (lines > maxLines) {
        return lines;
      }
    }
  }

  return content[content.length - 1] === 10 ? lines : lines + 1;
}

function generatedMarkerIn(content: string): boolean {
  const sample = content
    .split('\n')
    .slice(0, GENERATED_PREFIX_LINES)
    .join('\n');
  return GENERATED_MARKER_PATTERNS.some((pattern) => pattern.test(sample));
}

function isGeneratedFile(file: FileChange, repoPath: string, contentSource: DiffContextSource): boolean {
  if (file.patch && generatedMarkerIn(file.patch)) {
    return true;
  }

  if (contentSource.type !== 'working-tree') {
    const source = readGitSource(repoPath, file.filename, contentSource, GENERATED_PREFIX_BYTES);
    return source.type === 'content' ? generatedMarkerIn(source.content.toString('utf-8')) : false;
  }

  const filePath = filePathFor(repoPath, file.filename);
  if (!filePath) {
    return false;
  }

  const prefix = readPrefix(filePath, GENERATED_PREFIX_BYTES);
  return prefix ? generatedMarkerIn(prefix) : false;
}

/**
 * Return the scan-limit skip reason for a file without reading more content than needed.
 */
export function getFileLimitSkip(
  filename: string,
  repoPath: string,
  config?: ScanConfig,
  diffContextSource: DiffContextSource = { type: 'working-tree' }
): SkippedFile | undefined {
  const scan = effectiveScanConfig(config);
  const filePath = filePathFor(repoPath, filename);
  if (!filePath) {
    return undefined;
  }

  if (diffContextSource.type !== 'working-tree') {
    const source = readGitSource(repoPath, filename, diffContextSource, scan.maxFileBytes);
    if (source.type === 'unavailable') {
      return undefined;
    }
    if (source.type === 'too_large') {
      return { filename, reason: 'limit:file_size' };
    }

    const lines = countBufferLinesUpTo(source.content, scan.maxFileLines);
    if (lines > scan.maxFileLines) {
      return { filename, reason: 'limit:file_lines' };
    }

    return undefined;
  }

  if (!existsSync(filePath)) {
    return undefined;
  }

  try {
    const size = statSync(filePath).size;
    if (size > scan.maxFileBytes) {
      return { filename, reason: 'limit:file_size' };
    }
  } catch {
    return { filename, reason: 'limit:file_read' };
  }

  const lines = countLinesUpTo(filePath, scan.maxFileLines);
  if (lines === undefined) {
    return { filename, reason: 'limit:file_read' };
  }
  if (lines > scan.maxFileLines) {
    return { filename, reason: 'limit:file_lines' };
  }

  return undefined;
}

/**
 * Return scan-policy skips that can be decided before synthetic patch creation.
 */
export function getPrePatchFileSkip(
  filename: string,
  options: ScanPolicyOptions,
  file?: FileChange
): SkippedFile | undefined {
  const diffContextSource = options.diffContextSource ?? { type: 'working-tree' };
  const fileForGeneratedCheck: FileChange = file ?? {
    filename,
    status: 'added',
    additions: 0,
    deletions: 0,
  };

  const ignored = ignoredByBuiltinOrUser(filename, options.ignore);
  if (ignored) {
    return ignored;
  }

  if (!userIncludesFile(filename, options.ignore?.paths) && isGeneratedFile(fileForGeneratedCheck, options.repoPath, diffContextSource)) {
    return { filename, reason: 'ignored:generated' };
  }

  return getFileLimitSkip(filename, options.repoPath, options.scan, diffContextSource);
}

/**
 * Apply Warden's global file ignore policy and scan budgets.
 *
 * The budget pass intentionally keeps existing file order for now. If large PRs
 * need smarter coverage later, this is the place to add deterministic sampling
 * or scoring before the budget is consumed.
 */
export function applyScanPolicy(
  files: FileChange[],
  options: ScanPolicyOptions
): ApplyScanPolicyResult {
  const scan = effectiveScanConfig(options.scan);
  const diffContextSource = options.diffContextSource ?? { type: 'working-tree' };
  const enforceChangedLineBudget = options.enforceChangedLineBudget ?? true;
  const skippedFiles: SkippedFile[] = [];
  const eligible: ScannableFileChange[] = [];

  for (const file of files) {
    const prePatchSkip = getPrePatchFileSkip(file.filename, {
      ...options,
      diffContextSource,
    }, file);
    if (prePatchSkip) {
      skippedFiles.push(prePatchSkip);
      continue;
    }

    const patch = file.patch;
    if (!patch) {
      skippedFiles.push({ filename: file.filename, reason: 'limit:missing_patch' });
      continue;
    }

    eligible.push({ ...file, patch });
  }

  const selected: ScannableFileChange[] = [];
  let consumedChangedLines = 0;
  for (const file of eligible) {
    if (selected.length >= scan.maxFiles) {
      skippedFiles.push({ filename: file.filename, reason: 'limit:file_count' });
      continue;
    }

    const fileChangedLines = changedLines(file);
    if (enforceChangedLineBudget && consumedChangedLines + fileChangedLines > scan.maxChangedLines) {
      skippedFiles.push({ filename: file.filename, reason: 'limit:changed_lines' });
      continue;
    }

    selected.push(file);
    consumedChangedLines += fileChangedLines;
  }

  return { files: selected, skippedFiles };
}
