import { closeSync, existsSync, openSync, readSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import ignore from 'ignore';
import { DEFAULT_SCAN_LIMITS, type IgnoreConfig, type ScanConfig } from '../config/schema.js';
import { matchGlob } from '../triggers/matcher.js';
import type { FileChange, SkippedFile } from '../types/index.js';

const GENERATED_PREFIX_BYTES = 64 * 1024;
const GENERATED_PREFIX_LINES = 200;

const BUILTIN_IGNORE_PATTERNS = [
  '**/pnpm-lock.yaml',
  '**/package-lock.json',
  '**/yarn.lock',
  '**/Cargo.lock',
  '**/go.sum',
  '**/go.mod',
  '**/poetry.lock',
  '**/composer.lock',
  '**/Gemfile.lock',
  '**/Pipfile.lock',
  '**/bun.lockb',
  '**/*.min.js',
  '**/*.min.css',
  '**/*.bundle.js',
  '**/*.bundle.css',
  '**/*.map',
  '**/dist/**',
  '**/build/**',
  '**/node_modules/**',
  '**/vendor/**',
  '**/.next/**',
  '**/.nuxt/**',
  '**/out/**',
  '**/coverage/**',
  '**/.cache/**',
  '**/*.generated.*',
  '**/*.g.ts',
  '**/*.g.dart',
  '**/*.pb.go',
  '**/*_pb2.py',
  '**/*.designer.cs',
  '**/generated/**',
  '**/__generated__/**',
  '**/*.png',
  '**/*.jpg',
  '**/*.jpeg',
  '**/*.gif',
  '**/*.webp',
  '**/*.ico',
  '**/*.svg',
  '**/*.pdf',
  '**/*.zip',
  '**/*.tar',
  '**/*.tgz',
  '**/*.gz',
  '**/*.woff',
  '**/*.woff2',
  '**/*.ttf',
  '**/*.mp4',
  '**/*.mov',
  '**/*.sqlite',
  '**/*.db',
  '**/*.parquet',
  '**/*.csv',
  '**/*.tsv',
];

const GENERATED_MARKER_PATTERNS = [
  /@generated\b/i,
  /\bautomatically generated\b/i,
  /\bcode generated by\b/i,
  /\bgenerated from\b/i,
  /\bopenapi generator\b/i,
  /\bswagger codegen\b/i,
  /\bgraphql-codegen\b/i,
  /\bgenerated by protoc\b/i,
];

export interface ScanPolicyOptions {
  repoPath: string;
  ignore?: IgnoreConfig;
  scan?: ScanConfig;
}

export interface ApplyScanPolicyResult {
  files: FileChange[];
  skippedFiles: SkippedFile[];
}

function changedLines(file: FileChange): number {
  return file.additions + file.deletions;
}

function effectiveScanConfig(config?: ScanConfig): Required<ScanConfig> {
  return {
    ...DEFAULT_SCAN_LIMITS,
    ...config,
  };
}

function stripNegation(pattern: string): string {
  return pattern.startsWith('!') ? pattern.slice(1) : pattern;
}

function userIncludesFile(filename: string, paths?: string[]): boolean {
  return (paths ?? []).some((pattern) => pattern.startsWith('!') && matchGlob(stripNegation(pattern), filename));
}

function userIgnoresFile(filename: string, paths?: string[]): string | undefined {
  let ignoredPattern: string | undefined;
  for (const pattern of paths ?? []) {
    if (pattern.startsWith('!')) {
      if (matchGlob(stripNegation(pattern), filename)) {
        ignoredPattern = undefined;
      }
      continue;
    }
    if (matchGlob(pattern, filename)) {
      ignoredPattern = pattern;
    }
  }
  return ignoredPattern;
}

function ignoredByBuiltinOrUser(filename: string, config?: IgnoreConfig): SkippedFile | undefined {
  const matcher = ignore().add([...BUILTIN_IGNORE_PATTERNS, ...(config?.paths ?? [])]);
  if (!matcher.ignores(filename)) {
    return undefined;
  }

  const userPattern = userIgnoresFile(filename, config?.paths);
  if (userPattern) {
    return { filename, reason: 'ignored:user', pattern: userPattern };
  }

  return { filename, reason: 'ignored:builtin' };
}

function filePathFor(repoPath: string, filename: string): string | undefined {
  const root = resolve(repoPath);
  const filePath = resolve(join(repoPath, filename));
  if (filePath !== root && !filePath.startsWith(`${root}/`)) {
    return undefined;
  }
  return filePath;
}

function readPrefix(filePath: string, maxBytes: number): string | undefined {
  let fd: number | undefined;
  try {
    fd = openSync(filePath, 'r');
    const buffer = Buffer.alloc(maxBytes);
    const bytesRead = readSync(fd, buffer, 0, maxBytes, 0);
    return buffer.toString('utf-8', 0, bytesRead);
  } catch {
    return undefined;
  } finally {
    if (fd !== undefined) {
      closeSync(fd);
    }
  }
}

function countLinesUpTo(filePath: string, maxLines: number): number | undefined {
  let fd: number | undefined;
  try {
    fd = openSync(filePath, 'r');
    const buffer = Buffer.alloc(64 * 1024);
    let lines = 0;
    let sawBytes = false;
    let lastByteWasNewline = false;
    while (true) {
      const bytesRead = readSync(fd, buffer, 0, buffer.length, null);
      if (bytesRead === 0) {
        if (!sawBytes) return 0;
        return lastByteWasNewline ? lines : lines + 1;
      }
      sawBytes = true;
      for (let i = 0; i < bytesRead; i++) {
        if (buffer[i] === 10) {
          lines++;
          if (lines > maxLines) return lines;
        }
      }
      lastByteWasNewline = buffer[bytesRead - 1] === 10;
    }
  } catch {
    return undefined;
  } finally {
    if (fd !== undefined) {
      closeSync(fd);
    }
  }
}

function generatedMarkerIn(content: string): boolean {
  const sample = content
    .split('\n')
    .slice(0, GENERATED_PREFIX_LINES)
    .join('\n');
  return GENERATED_MARKER_PATTERNS.some((pattern) => pattern.test(sample));
}

function isGeneratedFile(file: FileChange, repoPath: string): boolean {
  if (file.patch && generatedMarkerIn(file.patch)) {
    return true;
  }

  const filePath = filePathFor(repoPath, file.filename);
  if (!filePath) {
    return false;
  }

  const prefix = readPrefix(filePath, GENERATED_PREFIX_BYTES);
  return prefix ? generatedMarkerIn(prefix) : false;
}

export function getFileLimitSkip(
  filename: string,
  repoPath: string,
  config?: ScanConfig
): SkippedFile | undefined {
  const scan = effectiveScanConfig(config);
  const filePath = filePathFor(repoPath, filename);
  if (!filePath) {
    return undefined;
  }
  if (!existsSync(filePath)) {
    return undefined;
  }

  try {
    const size = statSync(filePath).size;
    if (size > scan.maxFileBytes) {
      return { filename, reason: 'limit:file_size' };
    }
  } catch {
    return { filename, reason: 'limit:file_read' };
  }

  const lines = countLinesUpTo(filePath, scan.maxFileLines);
  if (lines === undefined) {
    return { filename, reason: 'limit:file_read' };
  }
  if (lines > scan.maxFileLines) {
    return { filename, reason: 'limit:file_lines' };
  }

  return undefined;
}

/**
 * Apply Warden's global file ignore policy and scan budgets.
 *
 * The budget pass intentionally keeps existing file order for now. If large PRs
 * need smarter coverage later, this is the place to add deterministic sampling
 * or scoring before the budget is consumed.
 */
export function applyScanPolicy(
  files: FileChange[],
  options: ScanPolicyOptions
): ApplyScanPolicyResult {
  const scan = effectiveScanConfig(options.scan);
  const skippedFiles: SkippedFile[] = [];
  const eligible: FileChange[] = [];

  for (const file of files) {
    const ignored = ignoredByBuiltinOrUser(file.filename, options.ignore);
    if (ignored) {
      skippedFiles.push(ignored);
      continue;
    }

    if (!userIncludesFile(file.filename, options.ignore?.paths) && isGeneratedFile(file, options.repoPath)) {
      skippedFiles.push({ filename: file.filename, reason: 'ignored:generated' });
      continue;
    }

    const limitSkip = getFileLimitSkip(file.filename, options.repoPath, options.scan);
    if (limitSkip) {
      skippedFiles.push(limitSkip);
      continue;
    }

    eligible.push(file);
  }

  const selected: FileChange[] = [];
  let consumedChangedLines = 0;
  for (const file of eligible) {
    if (selected.length >= scan.maxFiles) {
      skippedFiles.push({ filename: file.filename, reason: 'limit:file_count' });
      continue;
    }

    const fileChangedLines = changedLines(file);
    if (consumedChangedLines + fileChangedLines > scan.maxChangedLines) {
      skippedFiles.push({ filename: file.filename, reason: 'limit:changed_lines' });
      continue;
    }

    selected.push(file);
    consumedChangedLines += fileChangedLines;
  }

  return { files: selected, skippedFiles };
}
